# Generated by Django 3.2.6 on 2021-08-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='uploaded_images')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
